---
title: "Julies_2022"
author: 
date: "11/02/2022"
output:
  pdf_document: default
  word_document: default
  html_document: default
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown of Analysis started 20220708 - update 20220729Codes

for markdown help <http://rmarkdown.rstudio.com>.
```{r libraries}
library(lme4)
library(lmerTest)
library(dplyr)
library(ggplot2)
library(car)
```

## Data Entry

```{r data_entry}
#Data organizing
#####
#Prior to csv creation, I summed hitdivider.C and bite.C in excel to create aggression.C
df.clean<-read.csv("/Users/andersond/Downloads/20230515_relevant_data.csv")
df<-df.clean

# round the states to remove decimal
df$closedivider.S <-  round(df$closedivider.S, digits = 0)
df$outnest.S <- round(df$outnest.S, digits = 0)
```

```{r}
#### order ####
setEPS()
postscript("/Users/andersond/Desktop/order.eps",print.it = TRUE)
par(mfrow=c(2,2),oma=c(5,1,1,1),mar=c(0,5,1,1)) 
boxplot(df$aggression.C~df$order, cex.axis=1.25, cex.lab=1.5,xaxt="n", xlab="",ylab="Bites (#/10min)")
boxplot(df$closedivider.S~df$order, cex.axis=1.25, cex.lab=1.5, xaxt="n", xlab="",ylab="Close to divider (s/10min)")
boxplot(df$outnest.S~df$order, cex.axis=1.25, cex.lab =1.5,xlab = "", ylab="Out of Nest (s/10min)")
boxplot(df$lateralroll.C~df$order, cex.axis=1.25,cex.lab=1.5,xlab = "", ylab="Lateral Roll (#/10min)")
title(xlab="Trial Number",outer=TRUE,cex.lab=2)
dev.off()
#NOT USED
#boxplot(df.large$attmate.C~df.large$order, xlab = "Trial Number", ylab="Attack Mate")
```


```{r}
df$order <- as.factor(df$order)
# code for stats and plots for Dennis et al 2022 manuscript
# use this line for published script and supply this data file.
# df <- read.csv(file = "Julies_2022_SuppleTable_BehaviorData.csv")  
df$plot.label <- as.factor(paste(df$pairtype,df$int.sex,df$sex, sep="."))
df$plot.label.order.D <- df$plot.label # makes a duplicate column
df$plot.label.order.D <- factor(df$plot.label, levels = levels(df$plot.label)[c(1,3,6,8,5,7,2,4)]) # reorders data and levels for labels

# change the order to do the rest of the comparisons
levels(df$plot.label)
a.f.F.L <- df$plot.label == "femaleLarger.female.Female"
b.m.F.L <- df$plot.label == "femaleLarger.male.Female"
c.f.M.L <- df$plot.label == "maleLarger.female.Male"
d.m.M.L <- df$plot.label == "maleLarger.male.Male"
e.f.F.S <- df$plot.label == "maleLarger.female.Female"
f.m.F.S <- df$plot.label == "maleLarger.male.Female"
g.f.M.S <- df$plot.label == "femaleLarger.female.Male"
h.m.M.S <- df$plot.label == "femaleLarger.male.Male"

## create treatment codes
Codes <- matrix(0,nrow=8,ncol=8) #8 conditions
Codes[,1] <- rep(1,8)
Codes[2:8,2:8] <- diag(7)
# Codes
col.D = c("red","red","cyan","cyan","pink","pink", "blue","blue")
BarSpace <- c(0.5,1,2,1,3,1,2,1) #redo the codes
#model for pairwise comparisons

glm2plotagg <- glmer(data = df, aggression.C~ b.m.F.L + c.f.M.L + d.m.M.L + e.f.F.S + f.m.F.S + g.f.M.S + h.m.M.S + order + (1|ID)+(1|IntruderID),control=glmerControl(optimizer="bobyqa",optCtrl=list(maxfun=2e5)),family="poisson")

Magg <- vcov(glm2plotagg)[c(1:8),c(1:8)]
FEagg <- fixef(glm2plotagg)[c(1:8)]
Estimatesagg <- as.numeric(Codes %*% FEagg)
EstVaragg <- rep(0,length(Estimatesagg))
#
for(i in 1:8) EstVaragg[i] <- as.numeric(Codes[i,] %*% Magg %*% t(Codes)[,i])
EstSEagg <- sqrt(EstVaragg)

glm2plotclose <- glmer(data = df, df$closedivider.S~ b.m.F.L + c.f.M.L + d.m.M.L + e.f.F.S + f.m.F.S + g.f.M.S + h.m.M.S + order+ (1|ID)+(1|IntruderID), control= glmerControl(optimizer = "bobyqa", optCtrl = list(maxfun=2e5)), family = "poisson") ## 
Mclose <- vcov(glm2plotclose)[c(1:8),c(1:8)]
FEclose <- fixef(glm2plotclose)[c(1:8)]
Estimatesclose <- as.numeric(Codes %*% FEclose)
EstVarclose <- rep(0,length(Estimatesclose))
#
for(i in 1:8) EstVarclose[i] <- as.numeric(Codes[i,] %*% Mclose %*% t(Codes)[,i])
EstSEclose <- sqrt(EstVarclose)

glm2plotout <- lmer(data = df, outnest.S~ b.m.F.L + c.f.M.L + d.m.M.L + e.f.F.S + f.m.F.S + g.f.M.S + h.m.M.S + order+ (1|ID)+(1|IntruderID)) 

Mout <- vcov(glm2plotout)[c(1:8),c(1:8)]
FEout <- fixef(glm2plotout)[c(1:8)]
Estimatesout <- as.numeric(Codes %*% FEout)
EstVarout <- rep(0,length(Estimatesout))
#
for(i in 1:8) EstVarout[i] <- as.numeric(Codes[i,] %*% Mout %*% t(Codes)[,i])
EstSEout <- sqrt(EstVarout)

glm2plotroll <- glmer(data = df, df$lateralroll.C~ b.m.F.L + c.f.M.L + d.m.M.L + e.f.F.S + f.m.F.S + g.f.M.S + h.m.M.S + order+ (1|ID)+(1|IntruderID), control= glmerControl(optimizer = "bobyqa", optCtrl = list(maxfun=2e5)), family = "poisson") ## 
Mroll <- vcov(glm2plotroll)[c(1:8),c(1:8)]
FEroll <- fixef(glm2plotroll)[c(1:8)]
Estimatesroll <- as.numeric(Codes %*% FEroll)
EstVarroll <- rep(0,length(Estimatesroll))
#
for(i in 1:8) EstVarroll[i] <- as.numeric(Codes[i,] %*% Mroll %*% t(Codes)[,i])
EstSEroll <- sqrt(EstVarroll)
````

````{r}
setEPS()
postscript("/Users/andersond/Desktop/all4.eps",print.it = TRUE)

par(mfrow=c(2,2),oma=c(9,1,1,1),mar=c(0,5,.5,0)) 

plot(rep(c(1,2),4), exp(Estimatesagg),  pch = c(21,21,23,23,21,21,23,23), cex = c(2, 2, 2, 2, 1, 1, 1, 1), ylim=c(0, round(max(exp(Estimatesagg)) + 0.1*max(exp(Estimatesagg)),0)), cex.axis=1.25, cex.lab=1.5, xlim = c(0.75,2.25), xlab = "", xaxt = "n", ylab = "Bites (#/10min)", bg= col.D, col = "black")
# ? lines # there must be a better way but this hack will work
lines( x= c(1,2), y = exp(Estimatesagg[c(1,2)]), col = "red", lty = 1,lwd=2)
lines( x= c(1,2), y = exp(Estimatesagg[c(3,4)]), col = "cyan", lty = 2,lwd=2)
lines( x= c(1,2), y = exp(Estimatesagg[c(5,6)]), col = "pink", lty = 2,lwd=2)
lines( x= c(1,2), y = exp(Estimatesagg[c(7,8)]), col = "blue", lty = 1,lwd =2)

plot(rep(c(1,2),4), exp(Estimatesclose),  pch = c(21,21,23,23,21,21,23,23), cex = c(2, 2, 2, 2, 1, 1, 1, 1), ylim=c(0, round(max(exp(Estimatesclose)) + 0.1*max(exp(Estimatesclose)),0)), cex.axis=1.25, cex.lab=1.25, xlim = c(0.75,2.25), xlab = "", xaxt = "n", ylab = "Close to Divider (s/10min)", bg= col.D, col = "black")
# ? lines # there must be a better way but this hack will work
lines( x= c(1,2), y = exp(Estimatesclose[c(1,2)]), col = "red", lty = 1,lwd=2)
lines( x= c(1,2), y = exp(Estimatesclose[c(3,4)]), col = "cyan", lty = 2,lwd=2)
lines( x= c(1,2), y = exp(Estimatesclose[c(5,6)]), col = "pink", lty = 2,lwd=2)
lines( x= c(1,2), y = exp(Estimatesclose[c(7,8)]), col = "blue", lty = 1,lwd =2)


## plot out of nest from Estimates as reaction norm
plot(rep(c(1,2),4), Estimatesout,  pch = c(21,21,23,23,21,21,23,23), cex = c(2, 2, 2, 2, 1, 1, 1, 1), ylim=c(0, round(max(Estimatesout) + 0.1*max(Estimatesout),0)), xlim = c(0.75,2.25), xlab = "", xaxt = "n", cex.lab=1.5, cex.axis=1.25, ylab = "Out of Nest (s/10min)", bg= col.D, col = "black")
axis(1, at = c(1,2), labels = c("Female","Male"), cex.axis=1.5 )
axis(1, at = 1.5, line = 2, labels = c("Intruder Sex"), cex.axis=2,tick = FALSE)
lines( x= c(1,2), y = Estimatesout[c(1,2)], col = "red", lty = 1, lwd=2)
lines( x= c(1,2), y = Estimatesout[c(3,4)], col = "cyan", lty = 2, lwd =2)
lines( x= c(1,2), y = Estimatesout[c(5,6)], col = "pink", lty = 2, lwd =2)
lines( x= c(1,2), y = Estimatesout[c(7,8)], col = "blue", lty = 1, lwd =2)

plot(rep(c(1,2),4), exp(Estimatesroll),  pch = c(21,21,23,23,21,21,23,23), cex = c(2, 2, 2, 2, 1, 1, 1, 1), ylim=c(0, round(max(exp(Estimatesroll)) + 0.1*max(exp(Estimatesroll)),0)), cex.axis=1.25, cex.lab=1.25, xlim = c(0.75,2.25), xlab = "", xaxt = "n", ylab = "Lateral Rolls (#/10min)", bg= col.D, col = "black")
axis(1, at = c(1,2), labels = c("Female","Male"),cex.axis=1.5 )
axis(1, at = 1.5, line = 2, labels = c("Intruder Sex"), cex.axis=2,tick = FALSE)
# ? lines # there must be a better way but this hack will work
lines( x= c(1,2), y = exp(Estimatesroll[c(1,2)]), col = "red", lty = 1,lwd=2)
lines( x= c(1,2), y = exp(Estimatesroll[c(3,4)]), col = "cyan", lty = 2,lwd=2)
lines( x= c(1,2), y = exp(Estimatesroll[c(5,6)]), col = "pink", lty = 2,lwd=2)
lines( x= c(1,2), y = exp(Estimatesroll[c(7,8)]), col = "blue", lty = 1,lwd =2)
points(x=c(2.2,2.2,2.2,2.2),y=c(2.9,2.6,2.3,2.0),cex=c(2,2,1,1),pch=c(21,23,21,23),bg=c("red","cyan","pink","blue"))
dev.off()

```
